//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace exams
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public int Memberid { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string OtherName { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string PhoneNumber { get; set; }
        public string LocationAddress { get; set; }
        public string ResidentialAddress { get; set; }
        public string Email { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
        public string Sex { get; set; }
        public Nullable<int> Groupid { get; set; }
        public Nullable<int> Priorityid { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual Priority Priority { get; set; }
    }
}
